[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
exclude = [".git", "__pycache__", "venv"]

[tool.coverage.run]
branch = true
source = ["backend"]

[tool.coverage.report]
omit = ["*/tests/*", "*/__init__.py"]
show_missing = true
